import { AdminHeader } from "@/components/admin-header";
import { AdminLogoutButton } from "@/components/admin-logout-button";
import { AdminNav, type AdminSection } from "@/components/admin-nav";
import { eyebrowClass, fieldInputClass, panelClass } from "@/lib/ui";

function Pulse({ className = "h-4 w-24" }: { className?: string }) { return <span className={`inline-block animate-pulse rounded bg-slate-200 ${className}`} />; }
function Shell({ active, eyebrow, title, description, action, children }: { active: AdminSection; eyebrow: string; title: string; description: string; action?: React.ReactNode; children: React.ReactNode }) { return <main className="min-h-screen bg-[#f4f7f5] px-4 py-5 sm:px-6 sm:py-8"><div className="mx-auto max-w-6xl"><AdminHeader eyebrow={eyebrow} title={title} description={description}><div className="order-1 sm:order-2"><AdminLogoutButton /></div>{action ? <div className="order-2 sm:order-1">{action}</div> : null}</AdminHeader><AdminNav active={active} />{children}</div></main>; }
function Rows({ count = 4 }: { count?: number }) { return <div className="divide-y divide-slate-100">{Array.from({ length: count }, (_, i) => <div key={i} className="py-4"><Pulse className="h-4 w-2/5" /><div><Pulse className="mt-2 h-3 w-3/5" /></div></div>)}</div>; }

export function ReviewGeneratorLoading() { return <Shell active="reviews" eyebrow="Saha araçları" title="Yorum bağlantısı" description="Bağlantıyı oluştur, karta yaz ve yeni cold walk-in kaydı aç."><section className={`${panelClass} mt-6`}><div className="mb-5"><p className={eyebrowClass}>Google yorumları</p><h2 className="mt-1 text-xl font-black">Yorum bağlantısı oluştur</h2><p className="mt-2 text-sm text-slate-500">Maps bağlantısını yapıştır. Yorum linki hazırlanır ve işletme saha geçmişine eklenir.</p></div><label className="mb-2 block text-xs font-extrabold text-slate-600">Google Maps bağlantısı veya Place ID</label><div className="flex gap-2"><input disabled placeholder="https://maps.app.goo.gl/..." className={`${fieldInputClass} min-w-0 flex-1`} /><button disabled className="rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-black text-slate-500">Temizle</button><button disabled className="rounded-xl bg-slate-900 px-5 py-3 text-sm font-black text-white">Oluştur</button></div><div className="mt-4 flex justify-end border-t border-slate-100 pt-4 text-xs font-black text-slate-600">□ Birlikte saha modu</div></section></Shell>; }

export function AdminLoading() { return <Shell active="reviews" eyebrow="Saha araçları" title="Yorum bağlantısı" description="Bağlantıyı oluştur, karta yaz ve sonucu tek ekrandan takip et."><section className={`${panelClass} mt-6`}><div className="mb-5 flex justify-between"><div><p className={eyebrowClass}>Google yorumları</p><h2 className="mt-1 text-xl font-black">Yorum bağlantısı oluştur</h2><p className="mt-2 text-sm text-slate-500">Maps bağlantısını yapıştır. Yorum linki hazırlanır ve işletme otomatik olarak saha listene eklenir.</p></div><button className="text-xs font-bold text-slate-400">Temizle</button></div><label className="mb-2 block text-xs font-extrabold text-slate-600">Google Maps bağlantısı veya Place ID</label><div className="flex gap-2 max-sm:flex-col"><input disabled placeholder="https://maps.app.goo.gl/..." className={fieldInputClass} /><button disabled className="rounded-xl bg-slate-900 px-5 py-3 text-sm font-black text-white">Oluştur</button></div><div className="mt-4 flex justify-end border-t border-slate-100 pt-4 text-xs font-black text-slate-600">□ Birlikte saha modu</div></section><section className="mt-6 grid gap-3 sm:grid-cols-3">{["Toplam", "Emre", "Başar"].map((name) => <article key={name} className={panelClass}><p className={eyebrowClass}>{name}</p><Pulse className="mt-3 h-8 w-12" /><div className="mt-4 grid grid-cols-2 border-t pt-4"><Pulse /><Pulse /></div></article>)}</section><section className="mt-6"><p className={eyebrowClass}>Saha geçmişi</p><h2 className="mt-1 text-xl font-black">İşletmeler</h2><div className="mt-4 grid gap-3 lg:grid-cols-2">{[0,1,2,3].map((i) => <div key={i} className={panelClass}><Pulse className="h-5 w-2/5" /><Pulse className="mt-3 h-3 w-1/2" /><div className="mt-5 h-12 rounded-xl bg-slate-100" /></div>)}</div></section></Shell>; }
export function TransactionsLoading() { return <Shell active="transactions" eyebrow="Kasa hareketleri" title="Gelir Gider" description="Gelir ve giderleri ekle, düzenle ve geçmişi incele."><div className="mb-4 mt-6 flex justify-end gap-2"><button className="rounded-xl bg-emerald-600 px-3 py-2.5 text-xs font-black text-white">+ Gelir</button><button className="rounded-xl bg-rose-600 px-3 py-2.5 text-xs font-black text-white">− Gider</button></div><section><p className={eyebrowClass}>Son hareketler</p><h2 className="mt-1 text-xl font-black">Kayıtlar</h2><div className={`${panelClass} mt-5`}><Rows count={6} /></div></section></Shell>; }
export function FinanceLoading() { return <Shell active="finance" eyebrow="Finans" title="Analiz ve eşitleme" description="Satış, kayıt, hak ediş ve gerçek para hareketlerini karşılaştır."><div className="mt-6 flex justify-end"><div className="h-10 w-28 rounded-xl bg-white" /></div><section className="mt-4 grid gap-4 sm:grid-cols-3">{[0,1,2].map((i) => <div key={i} className={i === 0 ? "min-h-40 rounded-3xl bg-slate-900 p-5" : panelClass}><Pulse className={i === 0 ? "h-3 w-20 bg-white/20" : "h-3 w-20"} /><div><Pulse className={i === 0 ? "mt-4 h-8 w-32 bg-white/20" : "mt-4 h-8 w-32"} /></div></div>)}</section>{["Satışı gerçekte kim yaptı?", "Kim ne kadar almalı?", "Transferler"].map((title) => <section key={title} className={`${panelClass} mt-6`}><p className={eyebrowClass}>Finans</p><h2 className="mt-1 text-xl font-black">{title}</h2><div className="mt-5"><Rows count={2} /></div></section>)}</Shell>; }
export function LeadsLoading() { return <Shell active="leads" eyebrow="Takip listesi" title="Takipler" description="Mesaj, arama, mail ve sipariş takiplerini yönet."><section className="mt-6 grid gap-6 lg:grid-cols-[minmax(0,.72fr)_minmax(0,1.28fr)]"><section className={panelClass}><p className={eyebrowClass}>Yeni takip</p><h2 className="mt-1 text-xl font-black">Takip ekle</h2><div className="mt-5 space-y-4">{[0,1,2,3].map((i) => <div key={i} className="h-12 rounded-xl border border-slate-200 bg-slate-50" />)}</div></section><section className={panelClass}><p className={eyebrowClass}>Takip edilecekler</p><h2 className="mt-1 text-xl font-black">Kişiler ve işletmeler</h2><Rows /></section></section></Shell>; }
export function QrLoading() { return <Shell active="qr" eyebrow="Bağlantı araçları" title="QR oluşturucu" description="İstediğin herhangi bir bağlantı için QR kod oluştur."><section className={`${panelClass} mt-6`}><p className={eyebrowClass}>Genel QR aracı</p><h2 className="mt-1 text-lg font-black">Herhangi bir bağlantı için QR kodu</h2><p className="mt-2 text-sm text-slate-500">Bağlantıyı QR koduna dönüştür.</p><div className="mt-4 h-12 rounded-xl border border-slate-200 bg-slate-50" /></section></Shell>; }
export function MessagesLoading() { return <Shell active="messages" eyebrow="Gelen kutusu" title="İletişim mesajları" description="Ana siteden gönderilen talepleri incele."><section className={`${panelClass} mt-6`}><p className={eyebrowClass}>En yeni mesajlar</p><h2 className="mt-1 text-xl font-black">Talepler</h2><Rows /></section></Shell>; }
export function ProfilesLoading() { return <Shell active="profiles" eyebrow="Yönetim" title="Profil kartları" description="Kişisel link kartlarını buradan oluştur ve yönet." action={<span className="rounded-2xl bg-slate-900 px-5 py-3.5 text-sm font-bold text-white">+ Yeni profil</span>}><section className="mt-6 grid gap-4 md:grid-cols-2">{[0,1,2,3].map((i) => <div key={i} className={panelClass}><Pulse className="h-3 w-28" /><Pulse className="mt-3 h-6 w-36" /><Pulse className="mt-2 h-4 w-28" /><div className="mt-6 flex gap-3"><div className="h-10 w-24 rounded-xl bg-slate-300" /><div className="h-10 w-32 rounded-xl bg-slate-100" /></div></div>)}</section></Shell>; }
export function StockLoading() { return <Shell active="stock" eyebrow="Yönetim" title="Stok takibi" description="Kart stoklarını, giriş-çıkışları ve işlemi yapan kişiyi tek yerde takip et." action={<span className="rounded-full bg-white px-4 py-2 text-xs font-semibold text-slate-500 shadow-sm"><Pulse className="h-3 w-5" /> ürün · <Pulse className="h-3 w-8" /> adet</span>}><section className="mt-6 grid gap-6 lg:grid-cols-[minmax(0,0.78fr)_minmax(0,1.22fr)]"><div className={panelClass}><p className={eyebrowClass}>Yeni ürün</p><h2 className="mt-1 text-xl font-black">Stok ürünü ekle</h2><Rows count={3} /></div><div className={panelClass}><p className={eyebrowClass}>Ürünler</p><h2 className="mt-1 text-xl font-black">Mevcut stok</h2><Rows /></div></section><section className={`${panelClass} mt-6`}><p className={eyebrowClass}>Denetim kaydı</p><h2 className="mt-1 text-xl font-black">Stok hareketleri</h2><Rows /></section></Shell>; }
export function ProfileEditorLoading({ mode }: { mode: "create" | "edit" }) { return <Shell active="profiles" eyebrow="Profil kartları" title={mode === "create" ? "Yeni profil oluştur" : "Profili düzenle"} description="Profil bilgileri yükleniyor."><section className={`${panelClass} mt-6`}><Rows count={6} /></section></Shell>; }
